---
title: "Data Import"
author: "Yuning Wang"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

## Load in a dataset

```{r message=FALSE}
## reads in a dataset
#absolute path & relative path, use relative path!
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
skimr::skim(litters_data) 
view(litters_data)
```

## Load in the pups data

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## Parsing columns
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```


## Read in an excel file
```{r}
#mlb11_data = read_excel(path = "data/mlb11.xlsx",range = "A1:D7")  
## read the range and sheet--sheet = ""##
mlb11_data = read_excel(path = "data/mlb11.xlsx")
head(mlb11_data, 5)
```

## Read in SAS
```{r}
library(haven)
pulse_data = read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_data, 5)
```


## Export a result
```{r}
mlb11_data_subset = read_excel(path = "data/mlb11.xlsx",range = "A1:D7")  
## read the range and sheet--sheet = ""##
write_csv(mlb11_data_subset, path = "./data/mlb_subset.csv")
```

